const problemList1 = [
    {
      title: "Problem 1",
      difficulty: "Medium",
      acceptance: "80%",
      description: "qwertyuiopasdfghjklzxcvbnmmmmmmkkj",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 2",
      difficulty: "Easy",
      acceptance: "90%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 3",
      difficulty: "Hard",
      acceptance: "70%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 4",
      difficulty: "Medium",
      acceptance: "85%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 5",
      difficulty: "Easy",
      acceptance: "75%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 6",
      difficulty: "Hard",
      acceptance: "60%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 7",
      difficulty: "Medium",
      acceptance: "95%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 8",
      difficulty: "Hard",
      acceptance: "50%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 9",
      difficulty: "Easy",
      acceptance: "85%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 10",
      difficulty: "Medium",
      acceptance: "70%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    // Add more problem objects as needed
  ];


  const problemList2 = [
    {
      title: "Problem 11",
      difficulty: "Medium",
      acceptance: "80%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 12",
      difficulty: "Easy",
      acceptance: "90%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 13",
      difficulty: "Hard",
      acceptance: "70%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 14",
      difficulty: "Medium",
      acceptance: "85%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 15",
      difficulty: "Easy",
      acceptance: "75%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 16",
      difficulty: "Hard",
      acceptance: "60%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 17",
      difficulty: "Medium",
      acceptance: "95%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 18",
      difficulty: "Hard",
      acceptance: "50%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 19",
      difficulty: "Easy",
      acceptance: "85%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    {
      title: "Problem 20",
      difficulty: "Medium",
      acceptance: "70%",
      description: "qwertyuiopasdfghjklzxcvbnm",
      input: "abc",
      output: "ABC",
    },
    // Add more problem objects as needed
  ];




export { problemList1, problemList2};